# Generated by Django 5.0.4 on 2024-05-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_web', '0002_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='P_details',
            field=models.CharField(max_length=150),
        ),
    ]
