# Generated by Django 5.0.4 on 2024-05-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_web', '0005_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
    ]
