# Generated by Django 5.0.4 on 2024-05-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_web', '0006_feedback1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback1',
            new_name='Feedback',
        ),
    ]
