# Generated by Django 5.0.4 on 2024-05-11 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_web', '0007_rename_feedback1_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
