# Generated by Django 5.0.4 on 2024-05-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_web', '0012_orderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhistory',
            name='tax',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='total_amount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
