# Generated by Django 5.0.4 on 2024-05-27 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_web', '0013_orderhistory_tax_orderhistory_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='tax',
        ),
    ]
