# Generated by Django 5.0.4 on 2024-05-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_web', '0014_remove_orderhistory_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='date_ordered',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
